var professions = {
 "All Occupations": { 
"Management occupations": { 
"Chief executives": 1140,
"General and operations managers": 8560,
"Legislators": 370,
"Advertising and promotions managers": 120,
"Marketing managers": 280,
"Sales managers": 610,
"Public relations managers": 190,
"Administrative services managers": 1300,
"Computer and information systems managers": 400,
"Financial managers": 920,
"Training and development managers": 70,
"Human resources managers - all other": 160,
"Industrial production managers": 120,
"Purchasing managers": 80,
"Transportation - storage - and distribution managers": 550,
"Construction managers": 790,
"Education administrators - preschool and child care center/program": 170,
"Education administrators - elementary and secondary school": 660,
"Education administrators - postsecondary": 160,
"Education administrators - all other": 80,
"Engineering managers": 340,
"Food service managers": 340,
"Lodging managers": 140,
"Medical and health services managers": 830,
"Natural sciences managers": 490,
"Postmasters and mail superintendents": 170,
"Property - real estate - and community association managers": 400,
"Social and community service managers": 440,
"Managers - all other": 1510},
"Business and financial operations occupations": { 
"Wholesale and retail buyers - except farm products": 280,
"Purchasing agents - except wholesale - retail - and farm products": 760,
"Claims adjusters - examiners - and investigators": 260,
"Compliance officers - except agriculture - construction - health and safety - and transportation": 950,
"Cost estimators": 290,
"Emergency management specialists": 60,
"Employment - recruitment - and placement specialists": 450,
"Compensation - benefits - and job analysis specialists": 140,
"Training and development specialists": 360,
"Human resources - training - and labor relations specialists - all other": 500,
"Logisticians": 190,
"Management analysts": 570,
"Business operations specialists - all other": 2380,
"Accountants and auditors": 2180,
"Appraisers and assessors of real estate": 180,
"Budget analysts": 300,
"Financial analysts": 420,
"Personal financial advisors": 140,
"Insurance underwriters": 110,
"Loan counselors": 30,
"Loan officers": 410,
"Tax examiners - collectors - and revenue agents": 60,
"Tax preparers": 120,
"Financial specialists - all other": 290},
"Computer and mathematical science occupations": { 
"Computer programmers": 650,
"Computer software engineers - applications": 310,
"Computer software engineers - systems software": 280,
"Computer support specialists": 980,
"Computer systems analysts": 400,
"Database administrators": 170,
"Network and computer systems administrators": 890,
"Network systems and data communications analysts": 280,
"Computer specialists - all other": 490,
"Operations research analysts": 60},
"Architecture and engineering occupations": { 
"Architects - except landscape and naval": 180,
"Landscape architects": 40,
"Cartographers and photogrammetrists": 90,
"Surveyors": 510,
"Chemical engineers": 80,
"Civil engineers": 1410,
"Electrical engineers": 650,
"Electronics engineers - except computer": 110,
"Environmental engineers": 330,
"Health and safety engineers - except mining safety engineers and inspectors": 160,
"Industrial engineers": 140,
"Materials engineers": 50,
"Mechanical engineers": 350,
"Mining and geological engineers - including mining safety engineers": 100,
"Petroleum engineers": 1100,
"Engineers - all other": 590,
"Architectural and civil drafters": 300,
"Mechanical drafters": 130,
"Drafters - all other": 50,
"Civil engineering technicians": 340,
"Electrical and electronic engineering technicians": 730,
"Electro-mechanical technicians": 130,
"Environmental engineering technicians": 60,
"Industrial engineering technicians": 150,
"Engineering technicians - except drafters - all other": 440,
"Surveying and mapping technicians": 210},
"Life - physical - and social science occupations": { 
"Soil and plant scientists": 50,
"Microbiologists": 40,
"Zoologists and wildlife biologists": 840,
"Biological scientists - all other": 360,
"Conservation scientists": 180,
"Foresters": 100,
"Life scientists - all other": 180,
"Atmospheric and space scientists": 150,
"Chemists": 160,
"Environmental scientists and specialists - including health": 690,
"Geoscientists - except hydrologists and geographers": 390,
"Hydrologists": 60,
"Physical scientists - all other": 120,
"Economists": 50,
"Market research analysts": 130,
"Clinical - counseling - and school psychologists": 220,
"Urban and regional planners": 260,
"Anthropologists and archeologists": 100,
"Social scientists and related workers - all other": 180,
"Biological technicians": 390,
"Chemical technicians": 120,
"Geological and petroleum technicians": 350,
"Social science research assistants": 40,
"Environmental science and protection technicians - including health": 100,
"Forest and conservation technicians": 490,
"Life - physical - and social science technicians - all other": 560},
"Community and social services occupations": { 
"Substance abuse and behavioral disorder counselors": 260,
"Educational - vocational - and school counselors": 520,
"Marriage and family therapists": 40,
"Mental health counselors": 370,
"Rehabilitation counselors": 190,
"Counselors - all other": 90,
"Child - family - and school social workers": 840,
"Medical and public health social workers": 190,
"Mental health and substance abuse social workers": 360,
"Social workers - all other": 280,
"Health educators": 310,
"Social and human service assistants": 2150,
"Community and social service specialists - all other": 410,
"Clergy": 100,
"Directors - religious activities and education": 60},
"Legal occupations": { 
"Lawyers": 960,
"Administrative law judges - adjudicators - and hearing officers": 50,
"Paralegals and legal assistants": 670,
"Title examiners - abstractors - and searchers": 140,
},
"Education - training - and library occupations": { 
"Business teachers - postsecondary": 640,
"Computer science teachers - postsecondary": 130,
"Education teachers - postsecondary": 170,
"Vocational education teachers - postsecondary": 160,
"Preschool teachers - except special education": 670,
"Kindergarten teachers - except special education": 260,
"Elementary school teachers - except special education": 3930,
"Middle school teachers - except special and vocational education": 1280,
"Vocational education teachers - middle school": 30,
"Secondary school teachers - except special and vocational education": 2360,
"Vocational education teachers - secondary school": 300,
"Special education teachers - preschool - kindergarten - and elementary school": 660,
"Special education teachers - middle school": 210,
"Special education teachers - secondary school": 520,
"Adult literacy - remedial education - and GED teachers and instructors": 110,
"Self-enrichment education teachers": 260,
"Teachers and instructors - all other": 1410,
"Curators": 60,
"Museum technicians and conservators": 60,
"Librarians": 360,
"Library technicians": 250,
"Instructional coordinators": 430,
"Teacher assistants": 4120},
"Arts - design - entertainment - sports - and media occupations": { 
"Art directors": 30,
"Artists and related workers - all other": 110,
"Floral designers": 70,
"Graphic designers": 190,
"Interior designers": 30,
"Merchandise displayers and window trimmers": 130,
"Producers and directors": 70,
"Coaches and scouts": 240,
"Radio and television announcers": 170,
"Reporters and correspondents": 150,
"Public relations specialists": 300,
"Editors": 110,
"Technical writers": 90,
"Writers and authors": 70,
"Interpreters and translators": 70,
"Media and communication workers - all other": 90,
"Audio and video equipment technicians": 120,
"Broadcast technicians": 110,
"Photographers": 50,
"Media and communication equipment workers - all other": 50},
"Healthcare practitioner and technical occupations": { 
"Chiropractors": 50,
"Dentists - general": 140,
"Dietitians and nutritionists": 110,
"Optometrists": 60,
"Pharmacists": 390,
"Family and general practitioners": 560,
"Internists - general": 40,
"Obstetricians and gynecologists": 40,
"Pediatricians - general": 50,
"Psychiatrists": 30,
"Surgeons": 70,
"Physicians and surgeons - all other": 270,
"Physician assistants": 320,
"Registered nurses": 5010,
"Occupational therapists": 160,
"Physical therapists": 410,
"Recreational therapists": 40,
"Respiratory therapists": 180,
"Speech-language pathologists": 220,
"Veterinarians": 110,
"Health diagnosing and treating practitioners - all other": 100,
"Medical and clinical laboratory technologists": 280,
"Medical and clinical laboratory technicians": 510,
"Dental hygienists": 520,
"Cardiovascular technologists and technicians": 30,
"Diagnostic medical sonographers": 60,
"Radiologic technologists and technicians": 440,
"Emergency medical technicians and paramedics": 350,
"Pharmacy technicians": 630,
"Psychiatric technicians": 270,
"Surgical technologists": 80,
"Veterinary technologists and technicians": 160,
"Licensed practical and licensed vocational nurses": 590,
"Medical records and health information technicians": 640,
"Opticians - dispensing": 150,
"Health technologists and technicians - all other": 220,
"Occupational health and safety specialists": 310,
"Occupational health and safety technicians": 50,
"Healthcare practitioners and technical workers - all other": 280},
"Healthcare support occupations": { 
"Home health aides": 2150,
"Nursing aides - orderlies - and attendants": 1910,
"Psychiatric aides": 100,
"Massage therapists": 320,
"Dental assistants": 960,
"Medical assistants": 1030,
"Medical equipment preparers": 50,
"Medical transcriptionists": 110,
"Pharmacy aides": 40,
"Veterinary assistants and laboratory animal caretakers": 160,
"Healthcare support workers - all other": 540},
"Protective service occupations": { 
"First-line supervisors/managers of correctional officers": 70,
"First-line supervisors/managers of police and detectives": 290,
"First-line supervisors/managers of fire fighting and prevention workers": 170,
"First-line supervisors/managers - protective service workers - all other": 100,
"Fire fighters": 1060,
"Correctional officers and jailers": 1090,
"Detectives and criminal investigators": 110,
"Parking enforcement workers": 30,
"Police and sheriff's patrol officers": 1200,
"Animal control workers": 50,
"Private detectives and investigators": 100,
"Security guards": 2220,
"Lifeguards - ski patrol - and other recreational protective service workers": 470,
"Protective service workers - all other": 650},
"Food preparation and serving related occupations": { 
"Chefs and head cooks": 600,
"First-line supervisors/managers of food preparation and serving workers": 1080,
"Cooks - institution and cafeteria": 1100,
"Cooks - restaurant": 1860,
"Cooks - short order": 630,
"Cooks - all other": 100,
"Food preparation workers": 2540,
"Bartenders": 1580,
"Combined food preparation and serving workers - including fast food": 5760,
"Counter attendants - cafeteria - food concession - and coffee shop": 1940,
"Waiters and waitresses": 3790,
"Food servers - nonrestaurant": 120,
"Dining room and cafeteria attendants and bartender helpers": 470,
"Dishwashers": 1160,
"Hosts and hostesses - restaurant - lounge - and coffee shop": 650,
"Food preparation and serving related workers - all other": 180},
"Building and grounds cleaning and maintenance occupations": { 
"First-line supervisors/managers of housekeeping and janitorial workers": 460,
"First-line supervisors/managers of landscaping - lawn service - and groundskeeping workers": 120,
"Janitors and cleaners - except maids and housekeeping cleaners": 5670,
"Maids and housekeeping cleaners": 2790,
"Landscaping and groundskeeping workers": 790,
"Tree trimmers and pruners": 90,
"Grounds maintenance workers - all other": 130},
"Personal care and service occupations": { 
"Gaming supervisors": 50,
"First-line supervisors/managers of personal service workers": 250,
"Nonfarm animal caretakers": 430,
"Gaming dealers": 330,
"Gaming and sports book writers and runners": 340,
"Ushers - lobby attendants - and ticket takers": 280,
"Amusement and recreation attendants": 580,
"Entertainment attendants and related workers - all other": 160,
"Hairdressers - hairstylists - and cosmetologists": 570,
"Skin care specialists": 80,
"Baggage porters and bellhops": 310,
"Tour guides and escorts": 660,
"Transportation attendants - except flight attendants and baggage porters": 340,
"Child care workers": 1130,
"Personal and home care aides": 1590,
"Fitness trainers and aerobics instructors": 550,
"Recreation workers": 600,
"Residential advisors": 210,
},
"Sales and related occupations": { 
"First-line supervisors/managers of retail sales workers": 2920,
"First-line supervisors/managers of non-retail sales workers": 250,
"Cashiers": 6180,
"Counter and rental clerks": 820,
"Parts salespersons": 450,
"Retail salespersons": 11010,
"Advertising sales agents": 280,
"Insurance sales agents": 530,
"Travel agents": 260,
"Sales representatives - services - all other": 530,
"Sales representatives - wholesale and manufacturing - technical and scientific products": 370,
"Sales representatives - wholesale and manufacturing - except technical and scientific products": 1480,
"Demonstrators and product promoters": 220,
"Real estate brokers": 60,
"Real estate sales agents": 110,
"Sales engineers": 40,
"Sales and related workers - all other": 180},
"Office and administrative support occupations": { 
"First-line supervisors/managers of office and administrative support workers": 2740,
"Switchboard operators - including answering service": 280,
"Bill and account collectors": 630,
"Billing and posting clerks and machine operators": 1250,
"Bookkeeping - accounting - and auditing clerks": 4350,
"Payroll and timekeeping clerks": 710,
"Procurement clerks": 330,
"Tellers": 1250,
"Court - municipal - and license clerks": 250,
"Customer service representatives": 2690,
"Eligibility interviewers - government programs": 140,
"File clerks": 600,
"Hotel - motel - and resort desk clerks": 1030,
"Interviewers - except eligibility and loan": 160,
"Library assistants - clerical": 320,
"Loan interviewers and clerks": 280,
"New accounts clerks": 100,
"Order clerks": 220,
"Human resources assistants - except payroll and timekeeping": 390,
"Receptionists and information clerks": 3220,
"Reservation and transportation ticket agents and travel clerks": 1040,
"All other information and record clerks": 1200,
"Cargo and freight agents": 770,
"Couriers and messengers": 200,
"Police - fire - and ambulance dispatchers": 350,
"Dispatchers - except police - fire - and ambulance": 520,
"Meter readers - utilities": 140,
"Postal service clerks": 270,
"Postal service mail carriers": 430,
"Postal service mail sorters - processors - and processing machine operators": 520,
"Production - planning - and expediting clerks": 580,
"Shipping - receiving - and traffic clerks": 1270,
"Stock clerks and order fillers": 2940,
"Weighers - measurers - checkers - and samplers - recordkeeping": 40,
"Executive secretaries and administrative assistants": 4230,
"Legal secretaries": 400,
"Medical secretaries": 900,
"Secretaries - except legal - medical - and executive": 2820,
"Computer operators": 320,
"Data entry keyers": 360,
"Word processors and typists": 130,
"Insurance claims and policy processing clerks": 50,
"Office clerks - general": 8540,
"Office machine operators - except computer": 120,
"Office and administrative support workers - all other": 2150},
"Construction and extraction occupations": { 
"First-line supervisors/managers of construction trades and extraction workers": 1210,
"Boilermakers": 40,
"Brickmasons and blockmasons": 40,
"Carpenters": 3030,
"Carpet installers": 70,
"Tile and marble setters": 60,
"Cement masons and concrete finishers": 240,
"Construction laborers": 3000,
"Operating engineers and other construction equipment operators": 2770,
"Drywall and ceiling tile installers": 160,
"Electricians": 2160,
"Glaziers": 120,
"Insulation workers - mechanical": 110,
"Painters - construction and maintenance": 500,
"Plumbers - pipefitters - and steamfitters": 1840,
"Roofers": 290,
"Structural iron and steel workers": 180,
"Helpers--carpenters": 100,
"Helpers--electricians": 60,
"Helpers - construction trades - all other": 30,
"Construction and building inspectors": 290,
"Hazardous materials removal workers": 520,
"Highway maintenance workers": 110,
"Septic tank servicers and sewer pipe cleaners": 140,
"Construction and related workers - all other": 390,
"Derrick operators - oil and gas": 110,
"Rotary drill operators - oil and gas": 290,
"Service unit operators - oil - gas - and mining": 440,
"Earth drillers - except oil and gas": 160,
"Explosives workers - ordnance handling experts - and blasters": 60,
"Continuous mining machine operators": 40,
"Mining machine operators - all other": 250,
"Roustabouts - oil and gas": 2110,
"Helpers--extraction workers": 260,
"Extraction workers - all other": 120},
"Installation - maintenance - and repair occupations": { 
"First-line supervisors/managers of mechanics - installers - and repairers": 1020,
"Computer - automated teller - and office machine repairers": 350,
"Telecommunications equipment installers and repairers - except line installers": 810,
"Avionics technicians": 70,
"Electric motor - power tool - and related repairers": 60,
"Electrical and electronics repairers - commercial and industrial equipment": 180,
"Electrical and electronics repairers - powerhouse - substation - and relay": 50,
"Electronic home entertainment equipment installers and repairers": 50,
"Security and fire alarm systems installers": 110,
"Aircraft mechanics and service technicians": 1360,
"Automotive body and related repairers": 240,
"Automotive service technicians and mechanics": 1460,
"Bus and truck mechanics and diesel engine specialists": 660,
"Mobile heavy equipment mechanics - except engines": 1150,
"Motorboat mechanics": 80,
"Motorcycle mechanics": 40,
"Outdoor power equipment and other small engine mechanics": 60,
"Recreational vehicle service technicians": 40,
"Tire repairers and changers": 260,
"Control and valve installers and repairers - except mechanical door": 40,
"Heating - air conditioning - and refrigeration mechanics and installers": 470,
"Home appliance repairers": 110,
"Industrial machinery mechanics": 550,
"Maintenance and repair workers - general": 3750,
"Maintenance workers - machinery": 140,
"Millwrights": 190,
"Electrical power-line installers and repairers": 330,
"Telecommunications line installers and repairers": 350,
"Precision instrument and equipment repairers - all other": 170,
"Commercial divers": 70,
"Locksmiths and safe repairers": 50,
"Riggers": 90,
"Helpers--installation - maintenance - and repair workers": 590,
"Installation - maintenance - and repair workers - all other": 670},
"Production occupations": { 
"First-line supervisors/managers of production and operating workers": 690,
"Team assemblers": 140,
"Assemblers and fabricators - all other": 160,
"Bakers": 320,
"Butchers and meat cutters": 280,
"Meat - poultry - and fish cutters and trimmers": 3580,
"Machinists": 290,
"Welders - cutters - solderers - and brazers": 790,
"Bindery workers": 40,
"Job printers": 50,
"Prepress technicians and workers": 70,
"Printing machine operators": 110,
"Laundry and dry-cleaning workers": 350,
"Pressers - textile - garment - and related materials": 70,
"Sewing machine operators": 50,
"Cabinetmakers and bench carpenters": 120,
"Sawing machine setters - operators - and tenders - wood": 30,
"Woodworking machine setters - operators - and tenders - except sawing": 60,
"Power distributors and dispatchers": 40,
"Power plant operators": 350,
"Stationary engineers and boiler operators": 60,
"Water and liquid waste treatment plant and system operators": 640,
"Gas plant operators": 70,
"Petroleum pump system operators - refinery operators - and gaugers": 810,
"Plant and system operators - all other": 160,
"Separating - filtering - clarifying - precipitating - and still machine setters - operators - and tenders": 110,
"Crushing - grinding - and polishing machine setters - operators - and tenders": 80,
"Cutting and slicing machine setters - operators - and tenders": 30,
"Inspectors - testers - sorters - samplers - and weighers": 250,
"Dental laboratory technicians": 80,
"Packaging and filling machine operators and tenders": 190,
"Painters - transportation equipment": 110,
"Photographic processing machine operators": 90,
"Cooling and freezing equipment operators and tenders": 30,
"Helpers--production workers": 280,
"Production workers - all other": 170},
"Transportation and material moving occupations": { 
"Aircraft cargo handling supervisors": 160,
"First-line supervisors/managers of helpers - laborers - and material movers - hand": 390,
"First-line supervisors/managers of transportation and material-moving machine and vehicle operators": 390,
"Airline pilots - copilots - and flight engineers": 1050,
"Commercial pilots": 590,
"Air traffic controllers": 680,
"Airfield operations specialists": 60,
"Bus drivers - transit and intercity": 410,
"Bus drivers - school": 1160,
"Driver/sales workers": 690,
"Truck drivers - heavy and tractor-trailer": 2820,
"Truck drivers - light or delivery services": 1530,
"Taxi drivers and chauffeurs": 380,
"Motor vehicle operators - all other": 190,
"Sailors and marine oilers": 640,
"Captains - mates - and pilots of water vessels": 740,
"Motorboat operators": 30,
"Ship engineers": 240,
"Parking lot attendants": 90,
"Service station attendants": 560,
"Transportation inspectors": 180,
"Transportation workers - all other": 300,
"Conveyor operators and tenders": 420,
"Crane and tower operators": 130,
"Excavating and loading machine and dragline operators": 60,
"Industrial truck and tractor operators": 770,
"Cleaners of vehicles and equipment": 690,
"Laborers and freight - stock - and material movers - hand": 5200,
"Packers and packagers - hand": 930,
"Refuse and recyclable material collectors": 170,
"Material moving workers - all other": 600}}};
